server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # T?m istekleri index.html'e y?nlendir (Angular routing i?in gerekli)
    location / {
        try_files $uri $uri/ /index.html;
    }
}