"""Add Notification and source_item_id

Revision ID: a0a87eb8d7f6
Revises: 217d021be029
Create Date: 2026-08-12 10:15:35.620041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0a87eb8d7f6'
down_revision: Union[str, None] = '217d021be029'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Bildirimin gönderildiği kullanıcı'),
    sa.Column('message', sa.Text(), nullable=False, comment='Bildirim içeriği'),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='Bildirimin okunma durumu'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='Bildirim tipi (Örn: REJECTED_ITEM, MISSING_REPORT)'),
    sa.Column('reference_id', sa.Integer(), nullable=True, comment="İlgili kaydın ID'si (Örn: report_id veya report_item_id)"),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Benzersiz kayıt kimliği'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Kaydın oluşturulma tarihi'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Kaydın son güncellenme tarihi'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.add_column('report_items', sa.Column('source_item_id', sa.Integer(), nullable=True, comment="Bu satır başka bir rapordan (örneğin alta iletme durumunda) kopyalandıysa orijinal satırın ID'si"))
    op.create_index(op.f('ix_report_items_source_item_id'), 'report_items', ['source_item_id'], unique=False)
    op.create_foreign_key(None, 'report_items', 'report_items', ['source_item_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'report_items', type_='foreignkey')
    op.drop_index(op.f('ix_report_items_source_item_id'), table_name='report_items')
    op.drop_column('report_items', 'source_item_id')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
