# """devisiklik_aciklamasi

# Revision ID: 3fef1dcd58c8
# Revises: 901ae777f0b3
# Create Date: 2026-08-11 14:20:20.620062

# """
# from typing import Sequence, Union

# from alembic import op
# import sqlalchemy as sa
# from sqlalchemy.dialects import postgresql

# # revision identifiers, used by Alembic.
# revision: str = '3fef1dcd58c8'
# down_revision: Union[str, None] = '901ae777f0b3'
# branch_labels: Union[str, Sequence[str], None] = None
# depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     # 1. userrole enum tipinin veritabanında var olduğundan emin olun (yoksa oluşturur)
#     userrole_enum = postgresql.ENUM('ADMIN', 'MANAGER', 'USER', 'USER_MANAGER', name='userrole')
#     userrole_enum.create(op.get_bind(), checkfirst=True)
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('activity_reports', 'status',
#                existing_type=postgresql.ENUM('DRAFT', 'SAVED', 'PENDING', 'APPROVED', 'REJECTED', name='reportstatus'),
#                comment='Raporun durumu (PENDING / APPROVED / REJECTED)',
#                existing_comment='Raporun durumu (DRAFT / SAVED)',
#                existing_nullable=False)
#     op.alter_column('activity_reports', 'rejection_note',
#                existing_type=sa.TEXT(),
#                comment='Yönetici reddettiğinde girilen red nedeni',
#                existing_nullable=True)
#     op.alter_column('report_items', 'related_institutions',
#                existing_type=sa.TEXT(),
#                comment='İlgili/ilişkili kurum kuruluşlar (Sadece KORDINASYON_GEREKTIREN_ISLER için)',
#                existing_nullable=True)
#     op.alter_column('report_items', 'solution_proposals',
#                existing_type=sa.TEXT(),
#                comment='Çözüm önerileri (Sadece KORDINASYON_GEREKTIREN_ISLER için)',
#                existing_nullable=True)
#     op.alter_column('units', 'unit_type',
#                existing_type=postgresql.ENUM('DEPARTMENT', 'DIRECTORATE', 'SUB_UNIT', name='unittype'),
#                comment='Birim Tipi (DEPARTMENT, DIRECTORATE, SUB_UNIT)',
#                existing_nullable=False,
#                existing_server_default=sa.text("'SUB_UNIT'::unittype"))
#     op.create_index(op.f('ix_units_unit_type'), 'units', ['unit_type'], unique=False)
#     op.add_column('users', sa.Column('emaill', sa.String(length=255), nullable=True, comment='Kullanıcı e-posta adresi / Giriş kullanıcı adı'))
#     op.alter_column('users', 'email',
#                existing_type=sa.VARCHAR(length=255),
#                comment='Kullanıcı e-posta adresi / Giriş kullanıcı adı',
#                existing_nullable=False)
#     op.alter_column('users', 'hashed_password',
#                existing_type=sa.VARCHAR(length=255),
#                comment='Bcrypt ile şifrelenmiş parola',
#                existing_nullable=False)
#     op.alter_column('users', 'full_name',
#                existing_type=sa.VARCHAR(length=255),
#                comment='Ad Soyad',
#                existing_nullable=False)
#     op.alter_column('users', 'title',
#                existing_type=sa.VARCHAR(length=255),
#                type_=sa.String(length=150),
#                comment='Ünvan / Görev Tanımı (Örn: Yazılım Uzmanı, Şube Müdürü)',
#                existing_nullable=True)
#     op.alter_column('users', 'role',
#            existing_type=sa.VARCHAR(length=50),
#            type_=userrole_enum,
#            nullable=False,
#            comment='Sistem yetki rolü (ADMIN, MANAGER, USER)',
#            postgresql_using='role::userrole')  # <-- DEĞİŞEN KISIM
#     op.alter_column('users', 'is_active',
#                existing_type=sa.BOOLEAN(),
#                nullable=False,
#                comment='Kullanıcı hesabı aktif/pasif durumu',
#                existing_server_default=sa.text('true'))
#     op.alter_column('users', 'is_superuser',
#                existing_type=sa.BOOLEAN(),
#                nullable=False,
#                comment='Sistem yöneticisi (superuser) yetkisi',
#                existing_server_default=sa.text('false'))
#     op.alter_column('users', 'department_id',
#                existing_type=sa.INTEGER(),
#                comment="Bağlı olunan Daire Başkanlığı ID'si",
#                existing_nullable=True)
#     op.alter_column('users', 'directorate_id',
#                existing_type=sa.INTEGER(),
#                comment="Bağlı olunan Şube Müdürlüğü ID'si",
#                existing_nullable=True)
#     op.alter_column('users', 'unit_id',
#                existing_type=sa.INTEGER(),
#                comment="Bağlı olunan Birim ID'si",
#                existing_nullable=True)
#     op.alter_column('users', 'manager_id',
#                existing_type=sa.INTEGER(),
#                comment="Doğrudan yönetici ID'si",
#                existing_nullable=True)
#     op.alter_column('users', 'id',
#                existing_type=sa.INTEGER(),
#                comment='Benzersiz kayıt kimliği',
#                existing_nullable=False,
#                autoincrement=True)
#     op.alter_column('users', 'created_at',
#                existing_type=postgresql.TIMESTAMP(),
#                type_=sa.DateTime(timezone=True),
#                nullable=False,
#                comment='Kaydın oluşturulma tarihi',
#                existing_server_default=sa.text('CURRENT_TIMESTAMP'))
#     op.alter_column('users', 'updated_at',
#                existing_type=postgresql.TIMESTAMP(),
#                type_=sa.DateTime(timezone=True),
#                nullable=False,
#                comment='Kaydın son güncellenme tarihi',
#                existing_server_default=sa.text('CURRENT_TIMESTAMP'))
#     op.drop_constraint('users_email_key', 'users', type_='unique')
#     op.create_index(op.f('ix_users_department_id'), 'users', ['department_id'], unique=False)
#     op.create_index(op.f('ix_users_directorate_id'), 'users', ['directorate_id'], unique=False)
#     op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
#     op.create_index(op.f('ix_users_emaill'), 'users', ['emaill'], unique=True)
#     op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
#     op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
#     op.create_index(op.f('ix_users_manager_id'), 'users', ['manager_id'], unique=False)
#     op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
#     op.create_index(op.f('ix_users_unit_id'), 'users', ['unit_id'], unique=False)
#     op.create_foreign_key(None, 'users', 'units', ['directorate_id'], ['id'], ondelete='SET NULL')
#     op.create_foreign_key(None, 'users', 'users', ['manager_id'], ['id'], ondelete='SET NULL')
#     op.create_foreign_key(None, 'users', 'units', ['department_id'], ['id'], ondelete='SET NULL')
#     # ### end Alembic commands ###

#     # Geçersiz (0 olan) Foreign Key ilişkilerini NULL yap
#     op.execute("UPDATE users SET directorate_id = NULL WHERE directorate_id = 0 OR directorate_id NOT IN (SELECT id FROM units)")
#     op.execute("UPDATE users SET department_id = NULL WHERE department_id = 0 OR department_id NOT IN (SELECT id FROM units)")
#     op.execute("UPDATE users SET unit_id = NULL WHERE unit_id = 0 OR unit_id NOT IN (SELECT id FROM units)")

#     # Foreign Key ilişkilerini oluştur
#     op.create_foreign_key(None, 'users', 'units', ['directorate_id'], ['id'], ondelete='SET NULL')
#     op.create_foreign_key(None, 'users', 'users', ['manager_id'], ['id'], ondelete='SET NULL')
#     op.create_foreign_key(None, 'users', 'units', ['department_id'], ['id'], ondelete='SET NULL')

# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_constraint(None, 'users', type_='foreignkey')
#     op.drop_constraint(None, 'users', type_='foreignkey')
#     op.drop_constraint(None, 'users', type_='foreignkey')
#     op.drop_index(op.f('ix_users_unit_id'), table_name='users')
#     op.drop_index(op.f('ix_users_role'), table_name='users')
#     op.drop_index(op.f('ix_users_manager_id'), table_name='users')
#     op.drop_index(op.f('ix_users_id'), table_name='users')
#     op.drop_index(op.f('ix_users_full_name'), table_name='users')
#     op.drop_index(op.f('ix_users_emaill'), table_name='users')
#     op.drop_index(op.f('ix_users_email'), table_name='users')
#     op.drop_index(op.f('ix_users_directorate_id'), table_name='users')
#     op.drop_index(op.f('ix_users_department_id'), table_name='users')
#     op.create_unique_constraint('users_email_key', 'users', ['email'])
#     op.alter_column('users', 'updated_at',
#                existing_type=sa.DateTime(timezone=True),
#                type_=postgresql.TIMESTAMP(),
#                nullable=True,
#                comment=None,
#                existing_comment='Kaydın son güncellenme tarihi',
#                existing_server_default=sa.text('CURRENT_TIMESTAMP'))
#     op.alter_column('users', 'created_at',
#                existing_type=sa.DateTime(timezone=True),
#                type_=postgresql.TIMESTAMP(),
#                nullable=True,
#                comment=None,
#                existing_comment='Kaydın oluşturulma tarihi',
#                existing_server_default=sa.text('CURRENT_TIMESTAMP'))
#     op.alter_column('users', 'id',
#                existing_type=sa.INTEGER(),
#                comment=None,
#                existing_comment='Benzersiz kayıt kimliği',
#                existing_nullable=False,
#                autoincrement=True)
#     op.alter_column('users', 'manager_id',
#                existing_type=sa.INTEGER(),
#                comment=None,
#                existing_comment="Doğrudan yönetici ID'si",
#                existing_nullable=True)
#     op.alter_column('users', 'unit_id',
#                existing_type=sa.INTEGER(),
#                comment=None,
#                existing_comment="Bağlı olunan Birim ID'si",
#                existing_nullable=True)
#     op.alter_column('users', 'directorate_id',
#                existing_type=sa.INTEGER(),
#                comment=None,
#                existing_comment="Bağlı olunan Şube Müdürlüğü ID'si",
#                existing_nullable=True)
#     op.alter_column('users', 'department_id',
#                existing_type=sa.INTEGER(),
#                comment=None,
#                existing_comment="Bağlı olunan Daire Başkanlığı ID'si",
#                existing_nullable=True)
#     op.alter_column('users', 'is_superuser',
#                existing_type=sa.BOOLEAN(),
#                nullable=True,
#                comment=None,
#                existing_comment='Sistem yöneticisi (superuser) yetkisi',
#                existing_server_default=sa.text('false'))
#     op.alter_column('users', 'is_active',
#                existing_type=sa.BOOLEAN(),
#                nullable=True,
#                comment=None,
#                existing_comment='Kullanıcı hesabı aktif/pasif durumu',
#                existing_server_default=sa.text('true'))
#     op.alter_column('users', 'role',
#                existing_type=sa.Enum('ADMIN', 'MANAGER', 'USER', 'USER_MANAGER', name='userrole'),
#                type_=sa.VARCHAR(length=50),
#                nullable=True,
#                comment=None,
#                existing_comment='Sistem yetki rolü (ADMIN, MANAGER, USER)')

#     # Enum tipini veritabanından silin
#     userrole_enum = postgresql.ENUM('ADMIN', 'MANAGER', 'USER', 'USER_MANAGER', name='userrole')
#     userrole_enum.drop(op.get_bind(), checkfirst=True)
#     op.alter_column('users', 'title',
#                existing_type=sa.String(length=150),
#                type_=sa.VARCHAR(length=255),
#                comment=None,
#                existing_comment='Ünvan / Görev Tanımı (Örn: Yazılım Uzmanı, Şube Müdürü)',
#                existing_nullable=True)
#     op.alter_column('users', 'full_name',
#                existing_type=sa.VARCHAR(length=255),
#                comment=None,
#                existing_comment='Ad Soyad',
#                existing_nullable=False)
#     op.alter_column('users', 'hashed_password',
#                existing_type=sa.VARCHAR(length=255),
#                comment=None,
#                existing_comment='Bcrypt ile şifrelenmiş parola',
#                existing_nullable=False)
#     op.alter_column('users', 'email',
#                existing_type=sa.VARCHAR(length=255),
#                comment=None,
#                existing_comment='Kullanıcı e-posta adresi / Giriş kullanıcı adı',
#                existing_nullable=False)
#     op.drop_column('users', 'emaill')
#     op.drop_index(op.f('ix_units_unit_type'), table_name='units')
#     op.alter_column('units', 'unit_type',
#                existing_type=postgresql.ENUM('DEPARTMENT', 'DIRECTORATE', 'SUB_UNIT', name='unittype'),
#                comment=None,
#                existing_comment='Birim Tipi (DEPARTMENT, DIRECTORATE, SUB_UNIT)',
#                existing_nullable=False,
#                existing_server_default=sa.text("'SUB_UNIT'::unittype"))
#     op.alter_column('report_items', 'solution_proposals',
#                existing_type=sa.TEXT(),
#                comment=None,
#                existing_comment='Çözüm önerileri (Sadece KORDINASYON_GEREKTIREN_ISLER için)',
#                existing_nullable=True)
#     op.alter_column('report_items', 'related_institutions',
#                existing_type=sa.TEXT(),
#                comment=None,
#                existing_comment='İlgili/ilişkili kurum kuruluşlar (Sadece KORDINASYON_GEREKTIREN_ISLER için)',
#                existing_nullable=True)
#     op.alter_column('activity_reports', 'rejection_note',
#                existing_type=sa.TEXT(),
#                comment=None,
#                existing_comment='Yönetici reddettiğinde girilen red nedeni',
#                existing_nullable=True)
#     op.alter_column('activity_reports', 'status',
#                existing_type=postgresql.ENUM('DRAFT', 'SAVED', 'PENDING', 'APPROVED', 'REJECTED', name='reportstatus'),
#                comment='Raporun durumu (DRAFT / SAVED)',
#                existing_comment='Raporun durumu (PENDING / APPROVED / REJECTED)',
#                existing_nullable=False)
#     # ### end Alembic commands ###

"""devisiklik_aciklamasi

Revision ID: 3fef1dcd58c8
Revises: 901ae777f0b3
Create Date: 2026-08-11 14:20:20.620062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3fef1dcd58c8'
down_revision: Union[str, None] = '901ae777f0b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. 'userrole' ENUM tipini (yoksa) oluştur
    userrole_enum = postgresql.ENUM('ADMIN', 'MANAGER', 'USER', 'USER_MANAGER', name='userrole')
    userrole_enum.create(op.get_bind(), checkfirst=True)

    # 2. Activity reports & Report items alan düzenlemeleri
    op.alter_column('activity_reports', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'SAVED', 'PENDING', 'APPROVED', 'REJECTED', name='reportstatus'),
               comment='Raporun durumu (PENDING / APPROVED / REJECTED)',
               existing_comment='Raporun durumu (DRAFT / SAVED)',
               existing_nullable=False)
    op.alter_column('activity_reports', 'rejection_note',
               existing_type=sa.TEXT(),
               comment='Yönetici reddettiğinde girilen red nedeni',
               existing_nullable=True)
    op.alter_column('report_items', 'related_institutions',
               existing_type=sa.TEXT(),
               comment='İlgili/ilişkili kurum kuruluşlar (Sadece KORDINASYON_GEREKTIREN_ISLER için)',
               existing_nullable=True)
    op.alter_column('report_items', 'solution_proposals',
               existing_type=sa.TEXT(),
               comment='Çözüm önerileri (Sadece KORDINASYON_GEREKTIREN_ISLER için)',
               existing_nullable=True)

    # 3. Units tablosu düzenlemeleri
    op.alter_column('units', 'unit_type',
               existing_type=postgresql.ENUM('DEPARTMENT', 'DIRECTORATE', 'SUB_UNIT', name='unittype'),
               comment='Birim Tipi (DEPARTMENT, DIRECTORATE, SUB_UNIT)',
               existing_nullable=False,
               existing_server_default=sa.text("'SUB_UNIT'::unittype"))
    op.create_index(op.f('ix_units_unit_type'), 'units', ['unit_type'], unique=False)

    # 4. 'emaill' kolonunu güvenli şekilde ekleme (Verileri email'den kopyalar)
    op.add_column('users', sa.Column('emaill', sa.String(length=255), nullable=True, comment='Kullanıcı e-posta adresi / Giriş kullanıcı adı'))
    op.execute("UPDATE users SET emaill = email WHERE emaill IS NULL")
    op.alter_column('users', 'emaill', nullable=False)

    # 5. Users tablosu kolon güncellemeleri
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='Kullanıcı e-posta adresi / Giriş kullanıcı adı',
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               comment='Bcrypt ile şifrelenmiş parola',
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Ad Soyad',
               existing_nullable=False)
    op.alter_column('users', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               comment='Ünvan / Görev Tanımı (Örn: Yazılım Uzmanı, Şube Müdürü)',
               existing_nullable=True)
    
    # role alanını ENUM tipine cast ederek dönüştür
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=userrole_enum,
               nullable=False,
               comment='Sistem yetki rolü (ADMIN, MANAGER, USER)',
               postgresql_using='role::userrole')

    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment='Kullanıcı hesabı aktif/pasif durumu',
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment='Sistem yöneticisi (superuser) yetkisi',
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'department_id',
               existing_type=sa.INTEGER(),
               comment="Bağlı olunan Daire Başkanlığı ID'si",
               existing_nullable=True)
    op.alter_column('users', 'directorate_id',
               existing_type=sa.INTEGER(),
               comment="Bağlı olunan Şube Müdürlüğü ID'si",
               existing_nullable=True)
    op.alter_column('users', 'unit_id',
               existing_type=sa.INTEGER(),
               comment="Bağlı olunan Birim ID'si",
               existing_nullable=True)
    op.alter_column('users', 'manager_id',
               existing_type=sa.INTEGER(),
               comment="Doğrudan yönetici ID'si",
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               comment='Benzersiz kayıt kimliği',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               comment='Kaydın oluşturulma tarihi',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               comment='Kaydın son güncellenme tarihi',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # İndeksler
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_department_id'), 'users', ['department_id'], unique=False)
    op.create_index(op.f('ix_users_directorate_id'), 'users', ['directorate_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_emaill'), 'users', ['emaill'], unique=True)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_manager_id'), 'users', ['manager_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_unit_id'), 'users', ['unit_id'], unique=False)

    # 6. KRİTİK ADIM: Foreign Key oluşturmadan ÖNCE hatalı (0 veya karşılığı olmayan) ID'leri NULL yapıyoruz
    op.execute("UPDATE users SET directorate_id = NULL WHERE directorate_id = 0 OR directorate_id NOT IN (SELECT id FROM units)")
    op.execute("UPDATE users SET department_id = NULL WHERE department_id = 0 OR department_id NOT IN (SELECT id FROM units)")
    op.execute("UPDATE users SET unit_id = NULL WHERE unit_id = 0 OR unit_id NOT IN (SELECT id FROM units)")

    # 7. Artık Foreign Key ilişkileri güvenle kurulabilir
    op.create_foreign_key(None, 'users', 'units', ['directorate_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'users', 'users', ['manager_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'users', 'units', ['department_id'], ['id'], ondelete='SET NULL')


def downgrade() -> None:
    userrole_enum = postgresql.ENUM('ADMIN', 'MANAGER', 'USER', 'USER_MANAGER', name='userrole')

    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_unit_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_manager_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_emaill'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_directorate_id'), table_name='users')
    op.drop_index(op.f('ix_users_department_id'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               comment=None,
               existing_comment='Kaydın son güncellenme tarihi',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               comment=None,
               existing_comment='Kaydın oluşturulma tarihi',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Benzersiz kayıt kimliği',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'manager_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment="Doğrudan yönetici ID'si",
               existing_nullable=True)
    op.alter_column('users', 'unit_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment="Bağlı olunan Birim ID'si",
               existing_nullable=True)
    op.alter_column('users', 'directorate_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment="Bağlı olunan Şube Müdürlüğü ID'si",
               existing_nullable=True)
    op.alter_column('users', 'department_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment="Bağlı olunan Daire Başkanlığı ID'si",
               existing_nullable=True)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment=None,
               existing_comment='Sistem yöneticisi (superuser) yetkisi',
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment=None,
               existing_comment='Kullanıcı hesabı aktif/pasif durumu',
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'role',
               existing_type=userrole_enum,
               type_=sa.VARCHAR(length=50),
               nullable=True,
               comment=None,
               existing_comment='Sistem yetki rolü (ADMIN, MANAGER, USER)',
               postgresql_using='role::varchar')
    
    userrole_enum.drop(op.get_bind(), checkfirst=True)
    
    op.alter_column('users', 'title',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Ünvan / Görev Tanımı (Örn: Yazılım Uzmanı, Şube Müdürü)',
               existing_nullable=True)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Ad Soyad',
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Bcrypt ile şifrelenmiş parola',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Kullanıcı e-posta adresi / Giriş kullanıcı adı',
               existing_nullable=False)
    op.drop_column('users', 'emaill')
    op.drop_index(op.f('ix_units_unit_type'), table_name='units')
    op.alter_column('units', 'unit_type',
               existing_type=postgresql.ENUM('DEPARTMENT', 'DIRECTORATE', 'SUB_UNIT', name='unittype'),
               comment=None,
               existing_comment='Birim Tipi (DEPARTMENT, DIRECTORATE, SUB_UNIT)',
               existing_nullable=False,
               existing_server_default=sa.text("'SUB_UNIT'::unittype"))
    op.alter_column('report_items', 'solution_proposals',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Çözüm önerileri (Sadece KORDINASYON_GEREKTIREN_ISLER için)',
               existing_nullable=True)
    op.alter_column('report_items', 'related_institutions',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='İlgili/ilişkili kurum kuruluşlar (Sadece KORDINASYON_GEREKTIREN_ISLER için)',
               existing_nullable=True)
    op.alter_column('activity_reports', 'rejection_note',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Yönetici reddettiğinde girilen red nedeni',
               existing_nullable=True)
    op.alter_column('activity_reports', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'SAVED', 'PENDING', 'APPROVED', 'REJECTED', name='reportstatus'),
               comment='Raporun durumu (DRAFT / SAVED)',
               existing_comment='Raporun durumu (PENDING / APPROVED / REJECTED)',
               existing_nullable=False)