"""Add lists to activity_reports

Revision ID: fb42b25680c6
Revises: b429d77aa201
Create Date: 2026-08-20 09:11:12.495795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb42b25680c6'
down_revision: Union[str, None] = 'b429d77aa201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_reports', sa.Column('yapilan_is_ids', sa.JSON(), nullable=True, comment="Yapılan işlerin ID'leri"))
    op.add_column('activity_reports', sa.Column('yapilacak_is_ids', sa.JSON(), nullable=True, comment="Yapılacak işlerin ID'leri"))
    op.add_column('activity_reports', sa.Column('koordinasyon_is_ids', sa.JSON(), nullable=True, comment="Kord. işlerin ID'leri"))
    op.alter_column('activity_reports', 'year',
               existing_type=sa.INTEGER(),
               comment='Raporun ait olduğu yıl (örn: 2026)',
               existing_comment='Raporun ait olduğu yıl (Örn: 2026)',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_reports', 'year',
               existing_type=sa.INTEGER(),
               comment='Raporun ait olduğu yıl (Örn: 2026)',
               existing_comment='Raporun ait olduğu yıl (örn: 2026)',
               existing_nullable=False)
    op.drop_column('activity_reports', 'koordinasyon_is_ids')
    op.drop_column('activity_reports', 'yapilacak_is_ids')
    op.drop_column('activity_reports', 'yapilan_is_ids')
    # ### end Alembic commands ###
