"""Add active_token_jti to users

Revision ID: 1d645f33efb4
Revises: a0a87eb8d7f6
Create Date: 2026-08-12 12:59:26.544956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d645f33efb4'
down_revision: Union[str, None] = 'a0a87eb8d7f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active_token_jti', sa.String(length=255), nullable=True, comment='Aktif oturum token kimliği (Çoklu oturumu engellemek için)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'active_token_jti')
    # ### end Alembic commands ###
