"""item_level_status_and_creator

Revision ID: a6f323b3938e
Revises: 3fef1dcd58c8
Create Date: 2026-08-11 15:50:53.422528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6f323b3938e'
down_revision: Union[str, None] = '3fef1dcd58c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_reports', 'rejection_note')
    op.add_column('report_items', sa.Column('creator_id', sa.Integer(), nullable=True, comment="Bu satırı ekleyen kullanıcının ID'si"))
    op.add_column('report_items', sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='reportstatus'), nullable=False, server_default='PENDING', comment='Bu satırın durumu (PENDING / APPROVED / REJECTED)'))
    op.add_column('report_items', sa.Column('rejection_note', sa.Text(), nullable=True, comment='Yönetici satırı reddettiğinde girilen red nedeni'))
    op.create_index(op.f('ix_report_items_creator_id'), 'report_items', ['creator_id'], unique=False)
    op.create_index(op.f('ix_report_items_status'), 'report_items', ['status'], unique=False)
    op.create_foreign_key(None, 'report_items', 'users', ['creator_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'report_items', type_='foreignkey')
    op.drop_index(op.f('ix_report_items_status'), table_name='report_items')
    op.drop_index(op.f('ix_report_items_creator_id'), table_name='report_items')
    op.drop_column('report_items', 'rejection_note')
    op.drop_column('report_items', 'status')
    op.drop_column('report_items', 'creator_id')
    op.add_column('activity_reports', sa.Column('rejection_note', sa.TEXT(), autoincrement=False, nullable=True, comment='Yönetici reddettiğinde girilen red nedeni'))
    # ### end Alembic commands ###
