"""add_system_logs_table

Revision ID: b429d77aa201
Revises: 0147f3974ece
Create Date: 2026-08-17 11:01:03.037531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b429d77aa201'
down_revision: Union[str, None] = '0147f3974ece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_logs',
    sa.Column('user_id', sa.Integer(), nullable=True, comment="İşlemi yapan kullanıcı ID'si"),
    sa.Column('action', sa.String(length=100), nullable=False, comment='İşlem tipi (örn: LOGIN, LOGOUT, CREATE_REPORT)'),
    sa.Column('entity_type', sa.String(length=100), nullable=True, comment='Etkilenen varlık tipi (örn: REPORT, USER, vb.)'),
    sa.Column('entity_id', sa.Integer(), nullable=True, comment="Etkilenen varlık ID'si"),
    sa.Column('details', sa.JSON(), nullable=True, comment='İşlem ile ilgili JSON formatında detaylar'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='Kullanıcı IP adresi'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Benzersiz kayıt kimliği'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Kaydın oluşturulma tarihi'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Kaydın son güncellenme tarihi'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_logs_action'), 'system_logs', ['action'], unique=False)
    op.create_index(op.f('ix_system_logs_entity_id'), 'system_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_system_logs_entity_type'), 'system_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_system_logs_id'), 'system_logs', ['id'], unique=False)
    op.create_index(op.f('ix_system_logs_user_id'), 'system_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_logs_user_id'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_id'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_entity_type'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_entity_id'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_action'), table_name='system_logs')
    op.drop_table('system_logs')
    # ### end Alembic commands ###
