"""Add created_by_id to institutions

Revision ID: 87d5e73276e6
Revises: 1d645f33efb4
Create Date: 2026-08-13 14:18:43.741763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87d5e73276e6'
down_revision: Union[str, None] = '1d645f33efb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutions', sa.Column('created_by_id', sa.Integer(), nullable=True, comment="Kurumu ekleyen kullanıcının ID'si"))
    op.create_index(op.f('ix_institutions_created_by_id'), 'institutions', ['created_by_id'], unique=False)
    op.create_foreign_key(None, 'institutions', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'institutions', type_='foreignkey')
    op.drop_index(op.f('ix_institutions_created_by_id'), table_name='institutions')
    op.drop_column('institutions', 'created_by_id')
    # ### end Alembic commands ###
