"""Add ReportItemProposal

Revision ID: 0147f3974ece
Revises: 87d5e73276e6
Create Date: 2026-08-14 10:31:46.789784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0147f3974ece'
down_revision: Union[str, None] = '87d5e73276e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy.dialects import postgresql

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_item_proposals',
    sa.Column('manager_report_id', sa.Integer(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('category', postgresql.ENUM('YAPILAN_ISLER', 'YAPILACAK_ISLER', 'KORDINASYON_GEREKTIREN_ISLER', name='itemcategory', create_type=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('related_institutions', sa.Text(), nullable=True),
    sa.Column('solution_proposals', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='proposalstatus'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Benzersiz kayıt kimliği'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Kaydın oluşturulma tarihi'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Kaydın son güncellenme tarihi'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manager_report_id'], ['activity_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_item_proposals_id'), 'report_item_proposals', ['id'], unique=False)
    op.create_index(op.f('ix_report_item_proposals_manager_report_id'), 'report_item_proposals', ['manager_report_id'], unique=False)
    op.create_index(op.f('ix_report_item_proposals_target_user_id'), 'report_item_proposals', ['target_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_item_proposals_target_user_id'), table_name='report_item_proposals')
    op.drop_index(op.f('ix_report_item_proposals_manager_report_id'), table_name='report_item_proposals')
    op.drop_index(op.f('ix_report_item_proposals_id'), table_name='report_item_proposals')
    op.drop_table('report_item_proposals')
    # ### end Alembic commands ###
