"""normalize_users_unit_id_and_manager_constraint

Revision ID: 217d021be029
Revises: a6f323b3938e
Create Date: 2026-08-11 16:42:54.253886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '217d021be029'
down_revision: Union[str, None] = 'a6f323b3938e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Data migration: Copy department_id/directorate_id to unit_id if unit_id is null
    op.execute(
        """
        UPDATE users 
        SET unit_id = COALESCE(unit_id, directorate_id, department_id)
        WHERE unit_id IS NULL AND (directorate_id IS NOT NULL OR department_id IS NOT NULL)
        """
    )
    
    op.alter_column('users', 'emaill',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_comment='Kullanıcı e-posta adresi / Giriş kullanıcı adı')
    op.drop_index('ix_users_department_id', table_name='users')
    op.drop_index('ix_users_directorate_id', table_name='users')
    op.create_index('ix_unique_unit_manager', 'users', ['unit_id'], unique=True, postgresql_where=sa.text("role = 'MANAGER'"))
    op.drop_constraint('users_department_id_fkey', 'users', type_='foreignkey')
    op.drop_constraint('users_directorate_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'directorate_id')
    op.drop_column('users', 'department_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True, comment="Bağlı olunan Daire Başkanlığı ID'si"))
    op.add_column('users', sa.Column('directorate_id', sa.INTEGER(), autoincrement=False, nullable=True, comment="Bağlı olunan Şube Müdürlüğü ID'si"))
    op.create_foreign_key('users_directorate_id_fkey', 'users', 'units', ['directorate_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('users_department_id_fkey', 'users', 'units', ['department_id'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_unique_unit_manager', table_name='users', postgresql_where=sa.text("role = 'MANAGER'"))
    op.create_index('ix_users_directorate_id', 'users', ['directorate_id'], unique=False)
    op.create_index('ix_users_department_id', 'users', ['department_id'], unique=False)
    op.alter_column('users', 'emaill',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_comment='Kullanıcı e-posta adresi / Giriş kullanıcı adı')
    # ### end Alembic commands ###
